export const FETCH_BUNDLES_REQUEST = 'FETCH_BUNDLES_REQUEST'
export const FETCH_BUNDLES_SUCCESS = 'FETCH_BUNDLES_SUCCESS'
export const FETCH_BUNDLES_FAILURE = 'FETCH_BUNDLES_FAILURE'

export const FETCH_BUNDLE_REQUEST = 'FETCH_BUNDLE_REQUEST'
export const FETCH_BUNDLE_SUCCESS = 'FETCH_BUNDLE_SUCCESS'
export const FETCH_BUNDLE_FAILURE = 'FETCH_BUNDLE_FAILURE'

export const CREATE_BUNDLE_REQUEST = 'CREATE_BUNDLE_REQUEST'
export const CREATE_BUNDLE_SUCCESS = 'CREATE_BUNDLE_SUCCESS'
export const CREATE_BUNDLE_FAILURE = 'CREATE_BUNDLE_FAILURE'

export const PUSH_IN_BUNDLES = 'PUSH_IN_BUNDLES'

export const EDIT_BUNDLE_GENERAL_SETTING = 'EDIT_BUNDLE_GENERAL_SETTING'
export const EDIT_BUNDLE_CUSTOM_SETTING = 'EDIT_BUNDLE_CUSTOM_SETTING'

export const SAVE_BUNDLE_REQUEST = 'SAVE_BUNDLE_REQUEST'
export const SAVE_BUNDLE_SUCCESS = 'SAVE_BUNDLE_SUCCESS'
export const SAVE_BUNDLE_FAILURE = 'SAVE_BUNDLE_FAILURE'

export const SET_TOOLS_FILTER = 'SET_TOOLS_FILTER'
export const SET_BUNDLES_FILTER = 'SET_BUNDLES_FILTER'

export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION'
