export const GET_BUNDLES_REQUEST = 'GET_BUNDLES_REQUEST'
export const GET_BUNDLES_SUCCESS = 'GET_BUNDLES_SUCCESS'
export const GET_BUNDLES_FAILURE = 'GET_BUNDLES_FAILURE'

export const CREATE_BUNDLE_REQUEST = 'CREATE_BUNDLE_REQUEST'
export const CREATE_BUNDLE_SUCCESS = 'CREATE_BUNDLE_SUCCESS'
export const CREATE_BUNDLE_FAILURE = 'CREATE_BUNDLE_FAILURE'
